export const WorkflowEvents = {
  ANSWER_SUBMITTED: 'ANSWER_SUBMITTED',
  ANSWER_VALID: 'ANSWER_VALID',
  ANSWER_INVALID: 'ANSWER_INVALID',
  QUESTIONNAIRE_COMPLETED: 'QUESTIONNAIRE_COMPLETED',
  USER_INPUT: 'USER_INPUT',
  SYSTEM_EVENT: 'SYSTEM_EVENT',
};