import { AIQuestionConfig } from '../../../shared/domain/ai-question-config';
import { ProcessMode, QuestionType, RenderMode } from '../../../shared/domain/enums';
import { QuestionOption } from './option.domain';
import { ValidationRule } from './validation-rule.domain';

export type Question = {
  id?: string;
  questionnaireId: string;
  attribute: string;
  text: string;
  description?: string;
  questionType: QuestionType;
  renderMode: RenderMode;
  processMode: ProcessMode;
  index: number;
  isRequired: boolean;
  hasLink: boolean;
  tags: string[];
  previousQuestionId?: string;
  nextQuestionId?: string;
  childQuestionnaireId?: string;
  options?: QuestionOption[];
  optionListId?: string;
  aiConfig?: AIQuestionConfig;
  validationRules?: ValidationRule[];
  isActive: boolean;
  metadata?: Record<string, any>;
  createdAt: Date;
  updatedAt?: Date;
};
